#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.1.0-{branch}.{build}

# branches to build
branches:
  # whitelist
  only:
    - master
    - develop

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Ubuntu

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# scripts to run before build
before_build:
  - dotnet --info

# Build settings
build:
  verbosity: minimal


#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run tests against only selected assemblies and/or categories
test:
  assemblies:
    - '**\*.Tests.dll'

# to run your custom scripts instead of automatic tests
test_script:
  - dotnet test --test-adapter-path:. --logger:Appveyor

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'
