#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.0-{build}

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
os: Visual Studio 2015

#---------------------------------#
#       build configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic MSBuild
build_script:
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: msbuild biocs/core
  - ps: msbuild biocs/core.tests

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test:
  assemblies:
    - Biocs.Core.Tests.dll
