version: 1.0.{build}
build:
  verbosity: minimal

os: Visual Studio 2015

build_script:
  # dotnet info
  - ps: dotnet --info

  # Run dotnet new 
  - ps: mkdir "test\test-dotnet-new" -Force | Push-Location
  - ps: dotnet new --lang fsharp
  - ps: dotnet restore
  - ps: dotnet --verbose build
  - ps: dotnet --verbose run a b
  - ps: Pop-Location
