#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.1.0-{build}

# branches to build
branches:
  # whitelist
  only:
    - master
    - develop

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

# scripts to run before build
before_build:
  - ps: dotnet --info
  - ps: nuget restore biocs\biocs.sln

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test:
  assemblies:
    - Biocs.Core.Tests.dll
