<Project Sdk="Microsoft.NET.Sdk">

  <!-- Application -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Biocs.Core.Tests</AssemblyName>
    <RootNamespace>Biocs</RootNamespace>
  </PropertyGroup>

  <!-- Microsoft.Testing.Platform -->
  <PropertyGroup>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <OutputType>Exe</OutputType>
    <TestResultsDirectory>$([System.IO.Path]::Combine($(MSBuildProjectDirectory), 'TestResults'))</TestResultsDirectory>
    <CoverageOutput>$([System.IO.Path]::Combine($(TestResultsDirectory), 'mstest.xml'))</CoverageOutput>
    <CoverageSettings>$([System.IO.Path]::Combine($(MSBuildProjectDirectory), 'CodeCoverage.runsettings'))</CoverageSettings>
    <TestingPlatformCommandLineArguments>--coverage --coverage-output-format cobertura --coverage-output $(CoverageOutput) --coverage-settings $(CoverageSettings)</TestingPlatformCommandLineArguments>
  </PropertyGroup>

  <!-- Global Usings -->
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <!-- Build -->
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);CA1861</NoWarn>
  </PropertyGroup>
  
  <!-- Dependencies -->
  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.2.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\core\core.csproj" />
  </ItemGroup>

  <!-- Contents -->
  <ItemGroup>
    <Content Include="Deployments\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="TestResults\**" />
  </ItemGroup>
  
</Project>
