name: .NET

on:
  push:
    branches: [ "master" ]

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v6
    - name: Setup docfx
      run: dotnet tool update -g docfx
    - name: Build docs
      run: docfx
      working-directory: docfx_project
    - name: Upload pages artifact
      id: deployment
      uses: actions/upload-pages-artifact@v5
      with:
        path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5
